claw_controller:
  ros__parameters:
    in1_pin: 23 # modify value to the coorect pin number
    in2_pin: 24 # modify value to the coorect pin number
    enable_pin: 25 # modify value to the coorect pin number
    min_claw_value: 0.0 # 0V
    max_claw_value: 5.0 # 5V

ball_grabber:
  ros__parameters:
    min_claw_value: 1.5 # TODO: adjut this vallue
    min_claw_value: 3.5 # TODO: adjut this vallue