<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.21" /> 
    <xacro:property name="base_width" value="0.21" />
    <xacro:property name="base_height" value="0.025" />
    <xacro:property name="wheel_length" value="0.025" />
    <xacro:property name="wheel_radius" value="0.0525" />
    <xacro:property name="wheel_separation" value="0.125" />
    <xacro:property name="wheel_mass" value="2.0" />
    <xacro:property name="base_mass" value="10.0" />

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <!-- <mesh filename="package://my_robot_description/meshes/bases/base.obj" /> -->
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix color">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="${color}"/>
            </visual>
            <collision>
                <geometry>
                    <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}"/> -->
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"
                            xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left_front" color="green" />
    <xacro:wheel_link prefix="left_back" color="green" />
    <xacro:wheel_link prefix="right_front" color="red" />
    <xacro:wheel_link prefix="right_back" color="red"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius - (base_height / 2.0)}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="front_wheel_joint" params="prefix1 direction1 direction2"> 
        <joint name="${prefix1}_front_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix1}_front_wheel_link"/>
            <origin xyz="${direction1 * (wheel_separation / 2.0)} ${direction2 * ((base_width + wheel_length) / 2.0)} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:front_wheel_joint prefix1="left" direction1="1" direction2="1" />
    <xacro:front_wheel_joint prefix1="right" direction1="1" direction2="-1" />

    <xacro:macro name="back_wheel_joint" params="prefix1 direction1 direction2"> 
        <joint name="${prefix1}_back_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix1}_back_wheel_link"/>
            <origin xyz="${direction1 * (wheel_separation / 2.0)} ${direction2 * ((base_width + wheel_length) / 2.0)} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <mimic joint="${prefix1}_front_wheel_joint" multiplier="1" offset="0"/> 
        </joint>
    </xacro:macro>

    <xacro:back_wheel_joint prefix1="left" direction1="-1" direction2="1" />
    <xacro:back_wheel_joint prefix1="right" direction1="-1" direction2="-1" />
    
</robot>