<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.21" /> 
    <xacro:property name="base_width" value="0.19" />
    <xacro:property name="base_height" value="0.025" />
    <xacro:property name="wheels_base_width" value="0.015" />
    <xacro:property name="wheel_length" value="0.02" />
    <xacro:property name="wheel_radius" value="0.0525" />
    <xacro:property name="motor_length" value="0.005" />
    <xacro:property name="motor_radius" value="0.035" />

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <!-- <mesh filename="package://my_robot_description/meshes/bases/base.obj" /> -->
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="2.0" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheels_base_link" params="prefix direction color">
        <link name="${prefix}_wheels_base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${wheels_base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 ${direction * wheels_base_width / 2.0} 0" rpy="0 0 0"/>
                <material name="${color}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${wheels_base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 ${direction * wheels_base_width / 2.0} 0" rpy="0 0 0"/>
            </collision>
            <xacro:box_inertia m="0.3" l="${base_length}" w="${wheels_base_width}" h="${base_height}"
                            xyz="0 ${direction * wheels_base_width / 2.0} 0" rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheels_base_link prefix="left" direction="1" color="red" />
    <xacro:wheels_base_link prefix="right" direction="-1" color="green" />

    <xacro:macro name="motor_link" params="prefix">
        <link name="${prefix}_motor_link">
            <visual>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="purple"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
             <xacro:cylinder_inertia m="0.1" r="${motor_radius}" h="${motor_length}"
                            xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:motor_link prefix="left" />
    <xacro:motor_link prefix="right" />


    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
             <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_length}"
                            xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left_front" />
    <xacro:wheel_link prefix="left_back" />
    <xacro:wheel_link prefix="right_front" />
    <xacro:wheel_link prefix="right_back" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius - (base_height / 2.0)}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="base_wheels_base_joint" params="prefix direction"> 
        <joint name="base_${prefix}_wheels_base_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_wheels_base_link"/>
            <origin xyz="0 ${direction * base_width / 2.0} ${base_height / 2.0}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:base_wheels_base_joint prefix="left" direction="1" />
    <xacro:base_wheels_base_joint prefix="right" direction="-1" />

    <xacro:macro name="wheels_base_motor_joint" params="prefix direction"> 
        <joint name="${prefix}_wheels_base_${prefix}_motor_joint" type="continuous">
            <parent link="${prefix}_wheels_base_link"/>
            <child link="${prefix}_motor_link"/>
            <origin xyz="0 ${direction * (wheels_base_width + (motor_length / 2.0))} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheels_base_motor_joint prefix="left" direction="1" />
    <xacro:wheels_base_motor_joint prefix="right" direction="-1" />

    <xacro:macro name="wheels_base_wheel_joint" params="prefix1 prefix2 direction1 direction2"> 
        <joint name="${prefix1}_wheels_base_${prefix1}_${prefix2}_wheel_joint" type="continuous">
            <parent link="${prefix1}_wheels_base_link"/>
            <child link="${prefix1}_${prefix2}_wheel_link"/>
            <origin xyz="${direction1 * (motor_radius + wheel_radius)} ${direction2 * (wheels_base_width + (wheel_length / 2.0))} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <mimic joint="${prefix1}_wheels_base_${prefix1}_motor_joint" multiplier="1" offset="0"/> 
        </joint>
    </xacro:macro>

    <xacro:wheels_base_wheel_joint prefix1="left" prefix2="front" direction1="1" direction2="1" />
    <xacro:wheels_base_wheel_joint prefix1="left" prefix2="back" direction1="-1" direction2="1" />
    <xacro:wheels_base_wheel_joint prefix1="right" prefix2="front" direction1="1" direction2="-1" />
    <xacro:wheels_base_wheel_joint prefix1="right" prefix2="back" direction1="-1" direction2="-1" />
    
</robot>