controller_manager:
  ros__paremeters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheels_base_left_motor_joint']
    right_wheel_names: ['right_wheels_base_right_motor_joint']
    wheel_separation: 0.205
    wheel_radius: 0.0525

    use_stamped_vel: false
